/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param id
 * @param sender
 * @param recipient
 * @param size
 * @param createdAt
 * @param createdAtHeight
 * @param symbol
 * @param type
 * @param transactionHash
 */
@Serializable
data class IndexerTransferResponseObject(

    val id: kotlin.String,
    val sender: IndexerTransferResponseObjectSender,
    val recipient: IndexerTransferResponseObjectSender,
    val size: kotlin.String,
    val createdAt: kotlin.String,
    val createdAtHeight: kotlin.String,
    val symbol: kotlin.String,
    val type: IndexerTransferType,
    val transactionHash: kotlin.String
)
