/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param id
 * @param side
 * @param liquidity
 * @param type
 * @param market
 * @param marketType
 * @param price
 * @param size
 * @param fee
 * @param createdAt
 * @param createdAtHeight
 * @param orderId
 * @param clientMetadata
 * @param subaccountNumber
 */
@Serializable
data class IndexerFillResponseObject(

    val id: kotlin.String,
    val side: IndexerOrderSide,
    val liquidity: IndexerLiquidity,
    val type: IndexerFillType,
    val market: kotlin.String,
    val marketType: IndexerMarketType,
    val price: kotlin.String,
    val size: kotlin.String,
    val fee: kotlin.String,
    val createdAt: IndexerIsoString,
    val createdAtHeight: kotlin.String,
    val orderId: kotlin.String? = null,
    val clientMetadata: kotlin.String? = null,
    val subaccountNumber: kotlin.Double
)
