/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param ticker
 * @param rate
 * @param price
 * @param effectiveAt
 * @param effectiveAtHeight
 */
@Serializable
data class IndexerHistoricalFundingResponseObject(

    val ticker: kotlin.String,
    val rate: kotlin.String,
    val price: kotlin.String,
    val effectiveAt: IndexerIsoString,
    val effectiveAtHeight: kotlin.String
)
