/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param startedAt
 * @param ticker
 * @param resolution
 * @param low
 * @param high
 * @param &#x60;open&#x60;
 * @param close
 * @param baseTokenVolume
 * @param usdVolume
 * @param trades
 * @param startingOpenInterest
 * @param id
 */
@Serializable
data class IndexerCandleResponseObject(

    val startedAt: IndexerIsoString,
    val ticker: kotlin.String,
    val resolution: IndexerCandleResolution,
    val low: kotlin.String,
    val high: kotlin.String,
    val `open`: kotlin.String,
    val close: kotlin.String,
    val baseTokenVolume: kotlin.String,
    val usdVolume: kotlin.String,
    val trades: kotlin.Double,
    val startingOpenInterest: kotlin.String,
    val id: kotlin.String
)
