/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param market
 * @param status
 * @param side
 * @param size
 * @param maxSize
 * @param entryPrice
 * @param realizedPnl
 * @param createdAt
 * @param createdAtHeight
 * @param sumOpen
 * @param sumClose
 * @param netFunding
 * @param unrealizedPnl
 * @param closedAt
 * @param exitPrice
 * @param subaccountNumber
 */
@Serializable
data class IndexerPerpetualPositionResponseObject(

    val market: kotlin.String,
    val status: IndexerPerpetualPositionStatus,
    val side: IndexerPositionSide,
    val size: kotlin.String,
    val maxSize: kotlin.String,
    val entryPrice: kotlin.String,
    val realizedPnl: kotlin.String,
    val createdAt: IndexerIsoString,
    val createdAtHeight: kotlin.String,
    val sumOpen: kotlin.String,
    val sumClose: kotlin.String,
    val netFunding: kotlin.String,
    val unrealizedPnl: kotlin.String,
    val closedAt: IndexerIsoString? = null,
    val exitPrice: kotlin.String? = null,
    val subaccountNumber: kotlin.Double
)
