/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param symbol
 * @param side
 * @param size
 * @param assetId
 * @param subaccountNumber
 */
@Serializable
data class IndexerAssetPositionResponseObject(

    val symbol: kotlin.String,
    val side: IndexerPositionSide,
    val size: kotlin.String,
    val assetId: kotlin.String,
    val subaccountNumber: kotlin.Double
)
