package exchange.dydx.abacus.tests.payloads

internal class MarketConfigurationsMock {
    internal val configurations = """
        {
            "1INCH-USD":{
               "name":"1inch",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":180362122.33,
               "baseSymbol":"1INCH",
               "baseSymbolName":"1inch",
               "quoteSymbol":"USD",
               "largeSize":10000,
               "route":"/trade/1INCH-USD",
               "websiteLink":"https://1inch.io/",
               "whitepaperLink":"https://github.com/1inch",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/1inch/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/1inch.png",
               "primaryDescriptionKey":"1INCH_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"1INCH_SECONDARY_DESCRIPTION"
            },
            "AAVE-USD":{
               "name":"Aave",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":13392219.23,
               "baseSymbol":"AAVE",
               "baseSymbolName":"Aave",
               "quoteSymbol":"USD",
               "largeSize":150,
               "route":"/trade/AAVE-USD",
               "websiteLink":"https://aave.com/",
               "whitepaperLink":"https://github.com/aave/protocol-v2/blob/master/aave-v2-whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/aave/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/aave.png",
               "primaryDescriptionKey":"AAVE_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"AAVE_SECONDARY_DESCRIPTION"
            },
            "ADA-USD":{
               "name":"Cardano",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":33313246915,
               "baseSymbol":"ADA",
               "baseSymbolName":"Cardano",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/ADA-USD",
               "websiteLink":"https://cardano.org/",
               "whitepaperLink":"https://why.cardano.org/en/introduction/motivation/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/cardano/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/ada.png",
               "primaryDescriptionKey":"CARDANO_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"CARDANO_SECONDARY_DESCRIPTION"
            },
            "ALGO-USD":{
               "name":"Algorand",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":6261266780,
               "baseSymbol":"ALGO",
               "baseSymbolName":"Algorand",
               "quoteSymbol":"USD",
               "largeSize":25000,
               "route":"/trade/ALGO-USD",
               "websiteLink":"https://algorand.com/",
               "whitepaperLink":"https://algorand.com/technology/white-papers",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/algorand/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/algo.png",
               "primaryDescriptionKey":"ALGORAND_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ALGORAND_SECONDARY_DESCRIPTION"
            },
            "ATOM-USD":{
               "name":"Cosmos",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":225109380.67,
               "baseSymbol":"ATOM",
               "baseSymbolName":"Cosmos",
               "quoteSymbol":"USD",
               "largeSize":4000,
               "route":"/trade/ATOM-USD",
               "websiteLink":"https://cosmos.network/",
               "whitepaperLink":"https://v1.cosmos.network/resources/whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/cosmos/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/atom.png",
               "primaryDescriptionKey":"COSMOS_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"COSMOS_SECONDARY_DESCRIPTION"
            },
            "AVAX-USD":{
               "name":"Avalanche",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":223849627.32,
               "baseSymbol":"AVAX",
               "baseSymbolName":"Avalanche",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/AVAX-USD",
               "websiteLink":"https://www.avalabs.org/",
               "whitepaperLink":"https://assets.website-files.com/5d80307810123f5ffbb34d6e/6008d7bbf8b10d1eb01e7e16_Avalanche%20Platform%20Whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/avalanche/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/avax.png",
               "primaryDescriptionKey":"AVAX_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"AVAX_SECONDARY_DESCRIPTION"
            },
            "BCH-USD":{
               "name":"Bitcoin Cash",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":18909781.25,
               "baseSymbol":"BCH",
               "baseSymbolName":"Bitcoin Cash",
               "quoteSymbol":"USD",
               "largeSize":80,
               "route":"/trade/BCH-USD",
               "websiteLink":"https://bitcoincash.org/",
               "whitepaperLink":"https://bitcoincash.org/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/bitcoin-cash/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/bch.png",
               "primaryDescriptionKey":"BITCOIN_CASH_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"BITCOIN_CASH_SECONDARY_DESCRIPTION"
            },
            "CELO-USD":{
               "name":"Celo",
               "tags":[
               ],
               "circulatingSupply":433213075,
               "baseSymbol":"CELO",
               "baseSymbolName":"Celo",
               "quoteSymbol":"USD",
               "largeSize":17000,
               "route":"/trade/CELO-USD",
               "websiteLink":"https://celo.org",
               "whitepaperLink":"https://docs.celo.org",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/celo/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/celo.png",
               "primaryDescriptionKey":"CELO_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"CELO_SECONDARY_DESCRIPTION"
            },
            "BTC-USD":{
               "name":"Bitcoin",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":18882437,
               "baseSymbol":"BTC",
               "baseSymbolName":"Bitcoin",
               "quoteSymbol":"USD",
               "largeSize":1,
               "route":"/trade/BTC-USD",
               "websiteLink":"https://bitcoin.org/",
               "whitepaperLink":"https://bitcoin.org/bitcoin.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/bitcoin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/btc.png",
               "primaryDescriptionKey":"BITCOIN_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"BITCOIN_SECONDARY_DESCRIPTION",
               "displayStepSize":"0.0001",
               "displayTickSize":"1"
            },
            "COMP-USD":{
               "name":"Compound",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":6018895.26,
               "baseSymbol":"COMP",
               "baseSymbolName":"Compound",
               "quoteSymbol":"USD",
               "largeSize":150,
               "route":"/trade/COMP-USD",
               "websiteLink":"https://compound.finance/",
               "whitepaperLink":"https://compound.finance/documents/Compound.Whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/compound/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/comp.png",
               "primaryDescriptionKey":"COMPOUND_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"COMPOUND_SECONDARY_DESCRIPTION"
            },
            "CRV-USD":{
               "name":"Curve",
               "tags":[
                  "Governance"
               ],
               "circulatingSupply":428744352.63,
               "baseSymbol":"CRV",
               "baseSymbolName":"Curve",
               "quoteSymbol":"USD",
               "largeSize":10000,
               "route":"/trade/CRV-USD",
               "websiteLink":"https://curve.fi/",
               "whitepaperLink":"https://curve.fi/whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/curve-dao-token/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/crv.png",
               "primaryDescriptionKey":"CURVE_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"CURVE_SECONDARY_DESCRIPTION"
            },
            "DOGE-USD":{
               "name":"Dogecoin",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":132249672335,
               "baseSymbol":"DOGE",
               "baseSymbolName":"Dogecoin",
               "quoteSymbol":"USD",
               "largeSize":10000,
               "route":"/trade/DOGE-USD",
               "websiteLink":"https://dogecoin.com/",
               "whitepaperLink":"https://github.com/dogecoin/dogecoin",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/dogecoin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/doge.png",
               "primaryDescriptionKey":"DOGECOIN_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"DOGECOIN_SECONDARY_DESCRIPTION"
            },
            "DOT-USD":{
               "name":"Polkadot",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":987579314.96,
               "baseSymbol":"DOT",
               "baseSymbolName":"Polkadot",
               "quoteSymbol":"USD",
               "largeSize":2500,
               "route":"/trade/DOT-USD",
               "websiteLink":"https://polkadot.network/",
               "whitepaperLink":"https://polkadot.network/PolkaDotPaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/polkadot-new/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/dot.png",
               "primaryDescriptionKey":"POLKADOT_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"POLKADOT_SECONDARY_DESCRIPTION"
            },
            "ENJ-USD":{
               "name":"Enjin",
               "circulatingSupply":869924705.57,
               "baseSymbol":"ENJ",
               "baseSymbolName":"Enjin",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/ENJ-USD",
               "websiteLink":"https://enjin.io/",
               "whitepaperLink":"https://cdn.enjin.io/downloads/whitepapers/enjin-coin/en.pdf/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/enjin-coin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/enj.png",
               "primaryDescriptionKey":"ENJ_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ENJ_SECONDARY_DESCRIPTION"
            },
            "EOS-USD":{
               "name":"EOS",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":972153179.78,
               "baseSymbol":"EOS",
               "baseSymbolName":"EOS",
               "quoteSymbol":"USD",
               "largeSize":10000,
               "route":"/trade/EOS-USD",
               "websiteLink":"https://eos.io/",
               "whitepaperLink":"https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/eos/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/eos.png",
               "primaryDescriptionKey":"EOS_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"EOS_SECONDARY_DESCRIPTION"
            },
            "ETC-USD":{
               "name":"Ethereum Classic",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":133725169.89,
               "baseSymbol":"ETC",
               "baseSymbolName":"Ethereum Classic",
               "quoteSymbol":"USD",
               "largeSize":2000,
               "route":"/trade/ETC-USD",
               "websiteLink":"https://ethereumclassic.org/",
               "whitepaperLink":"https://ethereumclassic.org/why-classic",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/ethereum-classic/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/etc.png",
               "primaryDescriptionKey":"ETC_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ETC_SECONDARY_DESCRIPTION"
            },
            "ETH-USD":{
               "name":"Ethereum",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":118476951.94,
               "baseSymbol":"ETH",
               "baseSymbolName":"Ethereum",
               "quoteSymbol":"USD",
               "largeSize":20,
               "route":"/trade/ETH-USD",
               "websiteLink":"https://ethereum.org/",
               "whitepaperLink":"https://ethereum.org/whitepaper/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/ethereum/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/eth.png",
               "primaryDescriptionKey":"ETHEREUM_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ETHEREUM_SECONDARY_DESCRIPTION",
               "displayStepSize":"0.001",
               "displayTickSize":"0.1"
            },
            "FIL-USD":{
               "name":"Filecoin",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":127803620.00,
               "baseSymbol":"FIL",
               "baseSymbolName":"Filecoin",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/FIL-USD",
               "websiteLink":"https://filecoin.io/",
               "whitepaperLink":"https://filecoin.io/filecoin.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/filecoin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/fil.png",
               "primaryDescriptionKey":"FILECOIN_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"FILECOIN_SECONDARY_DESCRIPTION"
            },
            "HNT-USD":{
               "name":"Helium",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":116574413.74,
               "baseSymbol":"HNT",
               "baseSymbolName":"Helium",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/HNT-USD",
               "websiteLink":"https://www.helium.com",
               "whitepaperLink":"http://whitepaper.helium.com",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/helium/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/hnt.png",
               "primaryDescriptionKey":"HNT_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"HNT_SECONDARY_DESCRIPTION"
            },
            "ICP-USD":{
               "name":"Internet Computer",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":225440712.67,
               "baseSymbol":"ICP",
               "baseSymbolName":"Internet Computer",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/ICP-USD",
               "websiteLink":"https://dfinity.org",
               "whitepaperLink":"https://dfinity.org/whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/internet-computer/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/icp.png",
               "primaryDescriptionKey":"ICP_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ICP_SECONDARY_DESCRIPTION"
            },
            "ISO-USD": {
               "name":"Generic Isolated",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":18882437,
               "baseSymbol":"ISO",
               "baseSymbolName":"Isolated",
               "quoteSymbol":"USD",
               "largeSize":1,
               "route":"/trade/BTC-USD",
               "websiteLink":"https://bitcoin.org/",
               "whitepaperLink":"https://bitcoin.org/bitcoin.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/bitcoin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/btc.png",
               "primaryDescriptionKey":"BITCOIN_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"BITCOIN_SECONDARY_DESCRIPTION",
               "displayStepSize":"0.0001",
               "displayTickSize":"1"
            },
            "LINK-USD":{
               "name":"Chainlink",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":467009553.92,
               "baseSymbol":"LINK",
               "baseSymbolName":"Chainlink",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/LINK-USD",
               "websiteLink":"https://chain.link/",
               "whitepaperLink":"https://link.smartcontract.com/whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/chainlink/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/link.png",
               "primaryDescriptionKey":"CHAINLINK_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"CHAINLINK_SECONDARY_DESCRIPTION"
            },
            "LTC-USD":{
               "name":"Litecoin",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":69046819.85,
               "baseSymbol":"LTC",
               "baseSymbolName":"Litecoin",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/LTC-USD",
               "websiteLink":"https://litecoin.org/",
               "whitepaperLink":"https://litecoin.info/index.php/Main_Page",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/litecoin/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/ltc.png",
               "primaryDescriptionKey":"LITECOIN_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"LITECOIN_SECONDARY_DESCRIPTION"
            },
            "LUNA-USD":{
               "name":"Terra",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":354811756.38,
               "baseSymbol":"LUNA",
               "baseSymbolName":"Terra",
               "quoteSymbol":"USD",
               "largeSize":650,
               "route":"/trade/LUNA-USD",
               "websiteLink":"https://www.terra.money",
               "whitepaperLink":"https://assets.website-files.com/611153e7af981472d8da199c/618b02d13e938ae1f8ad1e45_Terra_White_paper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/terra-luna/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/luna.png",
               "primaryDescriptionKey":"LUNA_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"LUNA_SECONDARY_DESCRIPTION"
            },
            "MATIC-USD":{
               "name":"Polygon",
               "tags":[
                  "Layer 2"
               ],
               "circulatingSupply":6966682963,
               "baseSymbol":"MATIC",
               "baseSymbolName":"Polygon",
               "quoteSymbol":"USD",
               "largeSize":30000,
               "route":"/trade/MATIC-USD",
               "websiteLink":"https://polygon.technology/",
               "whitepaperLink":"https://polygon.technology/lightpaper-polygon.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/polygon/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/matic.png",
               "primaryDescriptionKey":"POLYGON_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"POLYGON_SECONDARY_DESCRIPTION"
            },
            "MKR-USD":{
               "name":"Maker",
               "tags":[
                  "Governance"
               ],
               "circulatingSupply":990069.94,
               "baseSymbol":"MKR",
               "baseSymbolName":"Maker",
               "quoteSymbol":"USD",
               "largeSize":20,
               "route":"/trade/MKR-USD",
               "websiteLink":"https://makerdao.com",
               "whitepaperLink":"https://makerdao.com/whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/maker/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/mkr.png",
               "primaryDescriptionKey":"MAKER_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"MAKER_SECONDARY_DESCRIPTION"
            },
            "NEAR-USD":{
               "name":"NEAR Protocol",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":664183154,
               "baseSymbol":"NEAR",
               "baseSymbolName":"NEAR Protocol",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/NEAR-USD",
               "websiteLink":"https://near.org",
               "whitepaperLink":"https://near.org/papers/the-official-near-white-paper/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/near-protocol/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/near.png",
               "primaryDescriptionKey":"NEAR_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"NEAR_SECONDARY_DESCRIPTION"
            },
            "RUNE-USD":{
               "name":"THORChain",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":330688061.33,
               "baseSymbol":"RUNE",
               "baseSymbolName":"THORChain",
               "quoteSymbol":"USD",
               "largeSize":6000,
               "route":"/trade/RUNE-USD",
               "websiteLink":"https://thorchain.org",
               "whitepaperLink":"https://whitepaper.io/document/709/thorchain-whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/thorchain/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/rune.png",
               "primaryDescriptionKey":"RUNE_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"RUNE_SECONDARY_DESCRIPTION"
            },
            "SNX-USD":{
               "name":"Synthetix",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":114841533.01,
               "baseSymbol":"SNX",
               "baseSymbolName":"Synthetix",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/SNX-USD",
               "websiteLink":"https://synthetix.io/",
               "whitepaperLink":"https://docs.synthetix.io/litepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/synthetix-network-token/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/snx.png",
               "primaryDescriptionKey":"SYNTHETIX_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"SYNTHETIX_SECONDARY_DESCRIPTION"
            },
            "SOL-USD":{
               "name":"Solana",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":309284697.05,
               "baseSymbol":"SOL",
               "baseSymbolName":"Solana",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/SOL-USD",
               "websiteLink":"https://solana.com/",
               "whitepaperLink":"https://solana.com/solana-whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/solana/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/sol.png",
               "primaryDescriptionKey":"SOLANA_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"SOLANA_SECONDARY_DESCRIPTION"
            },
            "SUSHI-USD":{
               "name":"Sushi",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":127244443,
               "baseSymbol":"SUSHI",
               "baseSymbolName":"Sushi",
               "quoteSymbol":"USD",
               "largeSize":4000,
               "route":"/trade/SUSHI-USD",
               "websiteLink":"https://sushi.com/",
               "whitepaperLink":"https://docs.sushi.com/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/sushiswap/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/sushi.png",
               "primaryDescriptionKey":"SUSHISWAP_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"SUSHISWAP_SECONDARY_DESCRIPTION"
            },
            "TRX-USD":{
               "name":"TRON",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":127244443,
               "baseSymbol":"TRX",
               "baseSymbolName":"TRON",
               "quoteSymbol":"USD",
               "largeSize":500000,
               "route":"/trade/TRX-USD",
               "websiteLink":"https://tron.network/",
               "whitepaperLink":"https://tron.network/static/doc/white_paper_v_2_0.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/tron/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/trx.png",
               "primaryDescriptionKey":"TRX_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"TRX_SECONDARY_DESCRIPTION"
            },
            "UMA-USD":{
               "name":"UMA",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":64359055.94,
               "baseSymbol":"UMA",
               "baseSymbolName":"UMA",
               "quoteSymbol":"USD",
               "largeSize":3000,
               "route":"/trade/UMA-USD",
               "websiteLink":"https://umaproject.org/",
               "whitepaperLink":"https://github.com/UMAprotocol/whitepaper",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/uma/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/uma.png",
               "primaryDescriptionKey":"UMA_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"UMA_SECONDARY_DESCRIPTION"
            },
            "UNI-USD":{
               "name":"Uniswap",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":627857378.77,
               "baseSymbol":"UNI",
               "baseSymbolName":"Uniswap",
               "quoteSymbol":"USD",
               "largeSize":1000,
               "route":"/trade/UNI-USD",
               "websiteLink":"https://uniswap.org/",
               "whitepaperLink":"https://uniswap.org/whitepaper-v3.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/uniswap/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/uni.png",
               "primaryDescriptionKey":"UNISWAP_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"UNISWAP_SECONDARY_DESCRIPTION"
            },
            "XLM-USD":{
               "name":"Stellar",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":24631765314,
               "baseSymbol":"XLM",
               "baseSymbolName":"Stellar",
               "quoteSymbol":"USD",
               "largeSize":200000,
               "route":"/trade/XLM-USD",
               "websiteLink":"https://www.stellar.org/",
               "whitepaperLink":"https://www.stellar.org/papers/stellar-consensus-protocol",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/stellar/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/xlm.png",
               "primaryDescriptionKey":"STELLAR_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"STELLAR_SECONDARY_DESCRIPTION"
            },
            "XMR-USD":{
               "name":"Monero",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":18035115.47,
               "baseSymbol":"XMR",
               "baseSymbolName":"Monero",
               "quoteSymbol":"USD",
               "largeSize":200,
               "route":"/trade/XMR-USD",
               "websiteLink":"https://www.getmonero.org/",
               "whitepaperLink":"https://www.getmonero.org/resources/research-lab/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/monero/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/xmr.png",
               "primaryDescriptionKey":"MONERO_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"MONERO_SECONDARY_DESCRIPTION"
            },
            "XTZ-USD":{
               "name":"Tezos",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":892771821.15,
               "baseSymbol":"XTZ",
               "baseSymbolName":"Tezos",
               "quoteSymbol":"USD",
               "largeSize":18000,
               "route":"/trade/XTZ-USD",
               "websiteLink":"https://tezos.com",
               "whitepaperLink":"https://tezos.com/whitepaper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/tezos/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/xtz.png",
               "primaryDescriptionKey":"XTZ_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"XTZ_SECONDARY_DESCRIPTION"
            },
            "YFI-USD":{
               "name":"Yearn",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":36637.72,
               "baseSymbol":"YFI",
               "baseSymbolName":"Yearn",
               "quoteSymbol":"USD",
               "largeSize":1,
               "route":"/trade/YFI-USD",
               "websiteLink":"https://yearn.finance/",
               "whitepaperLink":"https://docs.yearn.finance/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/yearn-finance/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/yfi.png",
               "primaryDescriptionKey":"YEARN_FINANCE_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"YEARN_FINANCE_SECONDARY_DESCRIPTION"
            },
            "ZEC-USD":{
               "name":"Zcash",
               "tags":[
                  "Layer 1"
               ],
               "circulatingSupply":13159681.25,
               "baseSymbol":"ZEC",
               "baseSymbolName":"Zcash",
               "quoteSymbol":"USD",
               "largeSize":300,
               "route":"/trade/ZEC-USD",
               "websiteLink":"https://z.cash/",
               "whitepaperLink":"https://z.cash/technology/",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/zcash/",
               "imageUrl":"https://media.dydx.exchange/currencies/zec.png",
               "primaryDescriptionKey":"ZCASH_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"ZCASH_SECONDARY_DESCRIPTION"
            },
            "ZRX-USD":{
               "name":"0x",
               "tags":[
                  "Defi"
               ],
               "circulatingSupply":845496054.80,
               "baseSymbol":"ZRX",
               "baseSymbolName":"0x",
               "quoteSymbol":"USD",
               "largeSize":30000,
               "route":"/trade/ZRX-USD",
               "websiteLink":"https://0x.org/",
               "whitepaperLink":"https://0x.org/pdfs/0x_white_paper.pdf",
               "coinMarketCapsLink":"https://coinmarketcap.com/currencies/0x/",
               "imageUrl":"https://s3.amazonaws.com/dydx.exchange/currencies/zrx.png",
               "primaryDescriptionKey":"0X_PRIMARY_DESCRIPTION",
               "secondaryDescriptionKey":"0X_SECONDARY_DESCRIPTION"
            }
         }
    """.trimIndent()
}
