# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

def abacus_pods
  pod 'abacus', :path => '../..'
  #pod 'abacus', :git => 'https://github.com/dydxprotocol/v4-abacus.git'
end


target 'abacus.ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for abacus.ios
  pod 'CryptoSwift'
  # pod 'ReachabilitySwift'
  abacus_pods

  target 'abacus.iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
