name: CI

on: 
  pull_request:
    paths:
      - '**/*.kt'

jobs:
  spotless:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: spotless
      run: |
        ./gradlew spotlessCheck

  detekt:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: detekt
        run: |
          ./gradlew detektMetadataMain
