name: SpotlessCheck

on: 
  pull_request:
    paths:
      - '**/*.kt'

jobs:
  spotlessCheck:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Lint Kotlin Files
      run: |
        ./gradlew spotlessCheck
